# Generated by Django 4.0.3 on 2022-04-05 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(default='pending', max_length=100)),
                ('attachment', models.FileField(upload_to=judge.models.get_uploaded_attachment_path)),
                ('passed_tests', models.IntegerField(default=-1)),
                ('total_tests', models.IntegerField(default=-1)),
                ('master_grade', models.IntegerField(default=-1)),
                ('output_log', models.TextField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('log_tests', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
