# Generated by Django 4.0.3 on 2022-04-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='attachment_content',
            field=models.BinaryField(default=b'', editable=True),
            preserve_default=False,
        ),
    ]
